/* ═══════════════════════════════════════════════════════
   FIXED LEVELS — from questions.xlsx (tools/embed_from_xlsx.py)
═══════════════════════════════════════════════════════ */
const FIXED_LEVELS=[
  {id:"lvl1",name:"LEVEL 1",icon:"🐍 🖥️ 💡",desc:"OOP Python · C Basics · Logic",badge:"easy",timerSeconds:30,damagePerHit:20,buffer:[
    {q:"What does OOP stand for?",opts:["Object Oriented Programming","Open Ordered Process","Object Operation Protocol","Output Oriented Processing"],ans:0},
    {q:"Which keyword is used to define a class in Python?",opts:["def","class","object","struct"],ans:1},
    {q:"What is the output?\nprint(type(42))",opts:["<class 'str'>","<class 'float'>","<class 'int'>","<class 'num'>"],ans:2},
    {q:"Which method is the constructor in Python?",opts:["__start__","__new__","__init__","__create__"],ans:2},
    {q:"In C, which header file is needed for printf()?",opts:["stdlib.h","string.h","stdio.h","math.h"],ans:2},
    {q:"What is the output?\nprint(10 % 3)",opts:["3","1","0","2"],ans:1},
    {q:"Which symbol is used for single-line comments in Python?",opts:["//","/*","#","--"],ans:2},
    {q:"What does 'self' refer to in a Python class?",opts:["The parent class","The current object","The class itself","A global variable"],ans:1},
    {q:"In C, what is the correct way to declare an integer variable?",opts:["integer x;","int x;","var x;","num x;"],ans:1},
    {q:"What is the output?\nprint(2 ** 4)",opts:["8","16","6","24"],ans:1},
    {q:"Which OOP concept hides internal data using private variables?",opts:["Inheritance","Polymorphism","Encapsulation","Abstraction"],ans:2},
    {q:"How do you create an object 'dog' from class 'Animal' in Python?",opts:["dog = Animal.new()","dog = new Animal()","dog = Animal()","dog = Animal.create()"],ans:2},
    {q:"What is the output in C?\nprintf(\"%d\", 5 + 3 * 2);",opts:["16","11","13","10"],ans:1},
    {q:"Which keyword is used for inheritance in Python?",opts:["extends","inherits","implements","class Child(Parent):"],ans:3},
    {q:"What does len() do in Python?",opts:["Returns last element","Returns the length","Deletes element","Sorts list"],ans:1},
    {q:"In C, what does scanf() do?",opts:["Prints to screen","Reads input from user","Opens a file","Allocates memory"],ans:1},
    {q:"What is the output?\nprint('Hello' * 3)",opts:["Hello3","HelloHelloHello","Error","Hello Hello Hello"],ans:1},
    {q:"Which OOP concept allows one class to use methods of another?",opts:["Encapsulation","Inheritance","Abstraction","Overloading"],ans:1},
    {q:"What is the output?\nx = [1,2,3]\nprint(x[0])",opts:["3","2","1","Error"],ans:2},
    {q:"In C, which loop is used when the number of iterations is unknown?",opts:["for","while","do-while","switch"],ans:1},
    {q:"What does 'pass' do in Python?",opts:["Ends the program","Does nothing - placeholder","Skips to next loop","Returns None"],ans:1},
    {q:"What is the output?\nprint(bool(0))",opts:["True","1","False","None"],ans:2},
    {q:"How do you access attribute 'name' of object 'p' in Python?",opts:["p->name","p[name]","p.name","p::name"],ans:2},
    {q:"In C, what is the size of char?",opts:["2 bytes","4 bytes","1 byte","8 bytes"],ans:2},
    {q:"Which of these is a mutable data type in Python?",opts:["tuple","string","list","int"],ans:2},
    {q:"What is the output?\nprint(10 // 3)",opts:["3.33","3","4","1"],ans:1},
    {q:"What is a class in OOP?",opts:["A function","A blueprint for objects","A variable","A loop"],ans:1},
    {q:"In C, how do you end every statement?",opts:["Period (.)","Colon (:)","Semicolon (;)","Comma (,)"],ans:2},
    {q:"What does the method __str__ do in Python?",opts:["Converts to integer","Returns string representation","Deletes object","Copies object"],ans:1},
    {q:"What is the output?\nprint(type('hello'))",opts:["<class 'int'>","<class 'char'>","<class 'str'>","<class 'string'>"],ans:2},
    {q:"Which keyword returns a value from a function?",opts:["give","send","return","output"],ans:2},
    {q:"In C, which operator is used for pointer dereference?",opts:["&","->","*","[]"],ans:2},
    {q:"What is output?\nfor i in range(3):\n    print(i)",opts:["1 2 3","0 1 2","0 1 2 3","1 2"],ans:1},
    {q:"What does __init__ receive as its first parameter always?",opts:["cls","this","self","obj"],ans:2},
    {q:"In C, which of these is a valid variable name?",opts:["2var","my-var","_myvar","int"],ans:2},
    {q:"What is the output?\nx = 5\nif x > 3:\n    print('Yes')",opts:["No","Yes","Error","None"],ans:1},
    {q:"What does append() do on a Python list?",opts:["Removes last item","Adds item to end","Sorts list","Reverses list"],ans:1},
    {q:"In OOP, what is an 'object'?",opts:["A function","An instance of a class","A data type","A loop"],ans:1},
    {q:"What is the output?\nprint(3 == 3)",opts:["3","1","True","Equal"],ans:2},
    {q:"In C, what does 'return 0' mean in main()?",opts:["Error occurred","Program ended successfully","Loop started","Memory freed"],ans:1},
    {q:"What is printed?\nprint(len([1,2,3,4]))",opts:["3","5","4","Error"],ans:2},
    {q:"Which method removes the last element of a list in Python?",opts:["remove()","delete()","pop()","clear()"],ans:2},
    {q:"What is the output?\nprint('a' in 'apple')",opts:["'a'","1","True","apple"],ans:2},
    {q:"In C, what is printf(\"%f\", 3.14); used for?",opts:["Print integer","Print float","Print char","Print string"],ans:1},
    {q:"Which loop runs at least once in C?",opts:["for","while","do-while","if"],ans:2},
    {q:"What is the output?\nprint(not True)",opts:["True","1","False","None"],ans:2},
    {q:"How do you define a method inside a class in Python?",opts:["method myMethod():","def myMethod(self):","function myMethod():","void myMethod():"],ans:1},
    {q:"In C, which format specifier is used for string?",opts:["%i","%d","%s","%c"],ans:2},
    {q:"What does 'break' do inside a loop?",opts:["Skips current iteration","Pauses loop","Exits the loop","Restarts loop"],ans:2},
    {q:"What is the output?\nprint([1,2,3][-1])",opts:["1","Error","2","3"],ans:3},
    {q:"If 2 + 2 = 4, then what is 2 * 3?",opts:["5","7","6","8"],ans:2},
  ]},
  {id:"lvl2",name:"LEVEL 2",icon:"⚡ 🔷 🧩",desc:"OOP Python · C · Logic",badge:"easy",timerSeconds:30,damagePerHit:20,buffer:[
    {q:"What is method overloading?",opts:["Two methods with same name, same params","Two methods with same name, different params","A child overrides parent","A class has two parents"],ans:1},
    {q:"What is the output?\nprint(5 > 3 and 2 < 4)",opts:["False","Error","1","True"],ans:3},
    {q:"In C, what happens when you access arr[5] of int arr[5]?",opts:["Returns 0","Compile error","Undefined behavior","Returns -1"],ans:2},
    {q:"What does 'continue' do in a loop?",opts:["Exits the loop","Skips current iteration and continues","Pauses loop","Restarts loop from beginning"],ans:1},
    {q:"What is the output?\nx = 'hello'\nprint(x.upper())",opts:["hello unchanged","HELLO","Error","hello123"],ans:1},
    {q:"In Python, which keyword creates a child class inheriting from Parent?",opts:["class Child::Parent","class Child extends Parent","class Child(Parent):","class Child inherit Parent:"],ans:2},
    {q:"In C, what is the value of 7 / 2 (integer division)?",opts:["3.5","3","4","2"],ans:1},
    {q:"What does isinstance(obj, MyClass) return?",opts:["The class name","True if obj is instance of MyClass","The object id","Error"],ans:1},
    {q:"What is printed?\nfor i in range(1,4):\n    print(i)\nOnly last print?",opts:["1","4","3","2"],ans:2},
    {q:"In C, what is a pointer?",opts:["A type of loop","A variable that stores memory address","A function return type","A constant"],ans:1},
    {q:"What is the output?\nprint(type(3.14))",opts:["<class 'int'>","<class 'double'>","<class 'float'>","<class 'decimal'>"],ans:2},
    {q:"Which OOP concept allows different classes to have methods with same name but different behavior?",opts:["Encapsulation","Inheritance","Polymorphism","Abstraction"],ans:2},
    {q:"In C, what does & mean in scanf(\"%d\", &x)?",opts:["Bitwise AND","Address of x","Reference to x","Logical AND"],ans:1},
    {q:"What is the output?\nprint(list(range(0,6,2)))",opts:["[0,2,4,6]","[0,2,4]","[2,4,6]","[1,3,5]"],ans:1},
    {q:"What is encapsulation?",opts:["Calling parent methods","Hiding data inside a class","Creating multiple objects","Using loops"],ans:1},
    {q:"In C, what is the correct way to create an array of 5 ints?",opts:["int arr{5};","int arr[5];","array int arr(5);","int[5] arr;"],ans:1},
    {q:"What does the 'super()' function do in Python?",opts:["Creates new object","Calls parent class method or constructor","Deletes object","Returns class name"],ans:1},
    {q:"What is the output?\nx = [1,2,3]\nx.append(4)\nprint(len(x))",opts:["3","5","4","Error"],ans:2},
    {q:"In C, which keyword is used to define a constant?",opts:["final","constant","const","static"],ans:2},
    {q:"If a class has no __init__, what happens when you create an object?",opts:["Error","Default __init__ is used","Object is None","Program crashes"],ans:1},
    {q:"What is the output?\nprint(10 != 10)",opts:["True","10","1","False"],ans:3},
    {q:"In C, which of these is a correct function definition?",opts:["function add(a,b):","int add(int a, int b) {}","def add(a, b):","void add = function() {}"],ans:1},
    {q:"What is abstraction in OOP?",opts:["Showing all details","Hiding complexity, showing only essentials","Creating objects","Using loops in class"],ans:1},
    {q:"What is the output?\nprint('5' + '3')",opts:["8","53","Error","'53'"],ans:1},
    {q:"In C, what does a void function return?",opts:["0","NULL","Nothing","False"],ans:2},
    {q:"What is the output?\nd = {'a':1,'b':2}\nprint(d['a'])",opts:["'a'","Error","a","1"],ans:3},
    {q:"How many times does this loop run?\nfor i in range(5):",opts:["4","6","5","0"],ans:2},
    {q:"In C, what is 'int *p;' declaring?",opts:["A pointer to int","An int named *p","An array of ints","A reference"],ans:0},
    {q:"What is the output?\nprint(2 == 2.0)",opts:["False","Error","1","True"],ans:3},
    {q:"Which of these correctly defines a class with one method in Python?",opts:["class Dog:\ndef bark(self): pass","class Dog:\n    def bark(self): pass","class Dog()\n    def bark(): pass","Dog class:\n    bark(): pass"],ans:1},
    {q:"What does 'None' represent in Python?",opts:["0","False","Empty list","The absence of a value"],ans:3},
    {q:"In C, what is sizeof(int) on most 32-bit systems?",opts:["1","2","8","4"],ans:3},
    {q:"What is the output?\nprint([1,2,3][1:3])",opts:["[1,2]","[2,3,4]","[2,3]","Error"],ans:2},
    {q:"Which method is called when an object is destroyed in Python?",opts:["__end__","__del__","__destroy__","__remove__"],ans:1},
    {q:"In C, the loop 'for(i=0;i<5;i++)' runs how many times?",opts:["4","6","5","Infinite"],ans:2},
    {q:"What is the output?\nprint(type(True))",opts:["<class 'int'>","<class 'bool'>","<class 'str'>","<class 'flag'>"],ans:1},
    {q:"What does 'private' access mean in OOP?",opts:["Accessible everywhere","Accessible only within the class","Accessible in child classes","Accessible in same file only"],ans:1},
    {q:"What is the output?\nprint(int(3.9))",opts:["4","3.9","3","Error"],ans:2},
    {q:"In C, which operator checks equality?",opts:["=","!=","==","==="],ans:2},
    {q:"What is the output?\nx = 10\nx += 5\nprint(x)",opts:["5","10","15","Error"],ans:2},
    {q:"In Python, which of these is an immutable type?",opts:["list","dict","set","tuple"],ans:3},
    {q:"A man has 3 apples and gives 1 away. How many remain?",opts:["3","1","2","4"],ans:2},
    {q:"If you count from 1 to 10, how many even numbers are there?",opts:["4","6","5","3"],ans:2},
    {q:"A class Animal has method speak(). Dog extends Animal and overrides speak(). This is?",opts:["Encapsulation","Overloading","Overriding","Abstraction"],ans:2},
    {q:"In C, printf(\"%d\", 10 > 5); prints?",opts:["5","10","0","1"],ans:3},
    {q:"What is the output?\nprint('python'[0])",opts:["p","python","Error","y"],ans:0},
    {q:"In Python, what does dict.keys() return?",opts:["List of values","List of keys","Count of items","Error"],ans:1},
    {q:"In C, what is an infinite loop?",opts:["while(0){}","for(;;){}","do{}while(false);","while(false){}"],ans:1},
    {q:"What is the output?\nprint(max(3, 1, 4, 1, 5))",opts:["1","4","3","5"],ans:3},
    {q:"What does the 'in' keyword do in Python?",opts:["Assignment","Checks membership","Comparison","Import"],ans:1},
  ]},
  {id:"lvl3",name:"LEVEL 3",icon:"🧠 📊 ⚡",desc:"Pool 3",badge:"medium",timerSeconds:30,damagePerHit:20,buffer:[
    {q:"TRUNCATE command is used for?",opts:["Remove specific rows", "Destroy Table", "Wipe all rows", "No such command exist"],ans:2},
    {q:"Which SQL clause is used after GROUP BY?",opts:["Where", "Having", "Order by", "select"],ans:1},
    {q:"Which is NOT a deadlock condition?",opts:["Mutual Exclusion", "Preemption", "Hold and Wait", "Circular Wait"],ans:1},
    {q:"What will be output?\nclass A { int x = 10; }\nclass B extends A { int x = 20; }\nB obj = new B(); System.out.print(obj.x);",opts:["10", "20", "error", "30"],ans:1},
    {q:"What happens when a constructor is not defined?",opts:["Object cannot be created", "Default constructor is created", "Runtime error", "Compile error"],ans:1},
    {q:"In Java, where are objects created using new stored?",opts:["Stack", "Heap", "Register", "Method Area"],ans:1},
    {q:"Which join returns all records when there is a match in either left or right table?",opts:["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN"],ans:3},
    {q:"Which of the following may eliminate deadlock without killing a process?",opts:["Resource \nPreemption", "Process Termination", "Ignoring Deadlock", "Rebooting the \nSystem"],ans:0},
    {q:"If a table is in 2NF, what must be true?",opts:["No multivalued \nattributes", "No transitive\n dependency", "No partial dependency", "No candidate key"],ans:2},
    {q:"Which concurrency protocol can cause deadlocks?",opts:["Timestamp \nOrdering", "Two-Phase Locking", "Multiversion \nConcurrency \nControl (MVCC)", "Optimistic \nConcurrency \nControl"],ans:1},
    {q:"Which NoSQL database is best suited for storing hierarchical data like\n folder structures?",opts:["Document DB", "Graph DB", "Column-family DB", "Key-value store"],ans:0},
    {q:"If 12 men do a job in 6 days, 18 men will take?",opts:["2", "3", "4", "5"],ans:2},
    {q:"A number is increased by 25% and becomes 125. Original number?",opts:["90", "95", "100", "105"],ans:2},
    {q:"Average of 5 numbers is 20. If one number is removed, average becomes 18. Removed number?",opts:["25", "26", "28", "30"],ans:2},
    {q:"A train crosses a pole in 10 sec at 72 km/h. Length of train?",opts:["150m", "180m", "200m", "220m"],ans:2},
    {q:"Profit = ₹200, Cost price = ₹800. Profit % = ?",opts:["0.2", "0.25", "0.3", "0.35"],ans:1},
    {q:"A sum doubles in 5 years (simple interest). Rate = ?",opts:["0.1", "0.12", "0.15", "0.2"],ans:3},
    {q:"A pipe fills tank in 6 hrs, another empties in 12 hrs. Net time?",opts:["8hrs", "12hrs", "14hrs", "19hrs"],ans:1},
    {q:"Mirror time of 3:40?",opts:["08:20:00", "09:20:00", "08:40:00", "09:40:00"],ans:0},
    {q:"If today is Wednesday, what day will it be after 100 days?",opts:["Friday", "Thursday", "Saturday", "Sunday"],ans:3},
    {q:"You are in a race. You pass the person in last place. What position are you now?",opts:["Last", "Second Last", "Impossible", "First"],ans:2},
    {q:"What is the output?\nint i=0;\nwhile(i++<3) cout<<i;",opts:["12", "123", "1234", "0123"],ans:1},
    {q:"What is a composite key?",opts:["A key made of two foreign keys", "A primary key that references another table", "A key formed by combining two or more columns", "An encrypted primary key"],ans:2},
    {q:"Shortest Remaining Time (SRT) is the preemptive version of which algorithm?",opts:["FCFS", "Round Robin", "SJF", "Priority Scheduling"],ans:2},
    {q:"What is the output?\nint a=5, b=2;\nprintf(\"%d\", a/b + a%b);",opts:["3", "4", "2", "5"],ans:0},
    {q:"What is the output?\nprint(list(map(lambda x: x*2, [1,2,3])))",opts:["[1,2,3]", "[2,4,6]", "[1,4,9]", "Error"],ans:1},
    {q:"Postfix expression for A + B * C is:",opts:["ABC*+", "AB+C*", "A+BC*", "ABC+*"],ans:0},
    {q:"What does ROLLBACK do in SQL?",opts:["Saves transaction permanently", "Deletes a table", "Undoes uncommitted changes", "Drops a database"],ans:2},
    {q:"What is the time complexity of building a heap from n elements?",opts:["O(n log n)", "O(n)", "O(log n)", "O(n^2)"],ans:1},
    {q:"What is the worst-case time complexity of searching in an AVL tree?",opts:["O(n)", "O(log n)", "O(n log n)", "O(1)"],ans:1},
    {q:"Which join is equivalent to a Cartesian Product?",opts:["Inner Join", "Left Join", "Cross Join", "Natural Join"],ans:2},
    {q:"Result of 5 ^ 3 (Bitwise XOR)?",opts:["8", "15", "6", "2"],ans:2},
    {q:"What is the output?\nx = [1]\nx.extend([2, 3])\nprint(len(x))",opts:["1", "2", "3", "4"],ans:2},
    {q:"Shortest path algorithm for a graph with no negative edges?",opts:["BFS", "DFS", "Dijkstra", "Kruskal"],ans:2},
    {q:"A class that cannot be instantiated but can be inherited is:",opts:["Final", "Abstract", "Static", "Sealed"],ans:1},
    {q:"Max number of edges in a simple undirected graph with $n$ vertices?",opts:["$n^2$", "$n(n-1)$", "$n(n-1)/2$", "$2n$"],ans:2},
    {q:"SQL clause used to filter after a GROUP BY?",opts:["WHERE", "HAVING", "ORDER BY", "LIMIT"],ans:1},
    {q:"What is the output?\nprintf(\"%d\", 10 >> 2);",opts:["40", "2", "5", "20"],ans:1},
    {q:"Belady’s Anomaly occurs in which page replacement?",opts:["LRU", "Optimal", "FIFO", "MRU"],ans:2},
    {q:"At 3:15, what is the angle between the hour and minute hand?",opts:["$0°$", "$7.5°$", "$15°$", "$22.5°$"],ans:1},
    {q:"Non-preemptive scheduling algorithm that can cause starvation?",opts:["Round Robin", "FCFS", "SJF", "Priority"],ans:2},
    {q:"A father is 3x the son's age. In 12 years, he'll be 2x. Son's age?",opts:["10", "12", "15", "18"],ans:1},
    {q:"In 2PL (Two-Phase Locking), the shrinking phase means:",opts:["No new locks; only releases", "Only acquires locks", "Both acquire and release", "Transaction ends"],ans:0},
    {q:"Which traversal visits the root LAST?",opts:["Preorder", "Inorder", "Postorder", "Level-order"],ans:2},
    {q:"What is the result?\nint a=2, b=3;\nprintf(\"%d\", a<<b);",opts:["6", "8", "16", "24"],ans:2},
    {q:"In Python, what does id() return?",opts:["Class name", "Memory address", "Object size", "Reference count"],ans:1},
    {q:"What is the output?\nres = list(map(lambda x: x**2, [1,2,3]))\nprint(res)",opts:["[1,2,3]", "[1,4,9]", "[2,4,6]", "Error"],ans:1},
    {q:"Which operator cannot be used with float in C?",opts:["*", "+", "%", "/"],ans:2},
  ]},
  {id:"lvl4",name:"LEVEL 4",icon:"🗄️ 🔍 📋",desc:"Pool 4",badge:"medium",timerSeconds:30,damagePerHit:20,buffer:[
    {q:"A table is in ____ if it is in 2NF and has no transitive dependencies.",opts:["1NF", "3NF", "BCNF", "4NF"],ans:1},
    {q:"What does the 'I' in ACID properties stand for?",opts:["Integration", "Integrity", "Isolation", "Iteration"],ans:2},
    {q:"Which constraint is used to ensure that a column cannot have NULL values?",opts:["UNIQUE", "NOT NULL", "CHECK", "DEFAULT"],ans:1},
    {q:"Which operator is used to deallocate memory?",opts:["delete", "remove", "free", "clear"],ans:0},
    {q:"Which feature allows a function to call itself?",opts:["Loops", "Overloading", "Recursion", "Inheritance"],ans:2},
    {q:"A schedule where conflicts are allowed but final result is equivalent to \nsome serial schedule is called:",opts:["Serializable \nschedule", "Strict schedule", "Recoverable schedule", "Preemptive \nschedule"],ans:0},
    {q:"25% of x = 40, x = ?",opts:["120", "140", "160", "180"],ans:2},
    {q:"Coding: CAT → DBU, DOG → ?",opts:["EPH", "EHP", "DPH", "EOG"],ans:0},
    {q:"A number divided by 5 gives remainder 3. What remainder when divided by 10?",opts:["3", "8", "13", "Cannot determine"],ans:3},
    {q:"If 1st Jan is Monday, what day is 10th Jan?",opts:["Tuesday", "Wednesday", "Thursday", "Friday"],ans:1},
    {q:"50% of 50% of 200 = ?",opts:["25", "50", "75", "100"],ans:1},
    {q:"If √x = 7, x = ?",opts:["36", "42", "49", "56"],ans:2},
    {q:"A train 100m long crosses 100m bridge at 10 m/s. Time?",opts:["10sec", "15sec", "20sec", "25sec"],ans:2},
    {q:"Which number replaces the question mark?\n2 → 6\n3 → 12\n4 → 20\n5 → ?",opts:["25", "30", "35", "40"],ans:1},
    {q:"A person walks 10m south, 10m east, 10m north. He is back at start. Where is he?",opts:["Anywhere", "Equator", "North Pole", "Desert"],ans:2},
    {q:"What does RAM stand for?",opts:["Read Access Memory", "Random Access Memory", "Rapid Access Module", "Runtime Access Memory"],ans:1},
    {q:"Which SQL command is used to add a new row to a table?",opts:["ADD", "UPDATE", "INSERT", "APPEND"],ans:2},
    {q:"What is the correct way to declare a constant in C?",opts:["constant int x=5", "const int x=5", "int const=5", "#define x int 5"],ans:1},
    {q:"What is the output?\nprint(type([]))",opts:["list", "<class 'list'>", "[]", "array"],ans:1},
    {q:"What is the output?\nint x=5;\nint &ref=x;\nref++;\ncout<<x;",opts:["5", "6", "Error", "Undefined"],ans:1},
    {q:"In which page replacement policy does the page not used for the longest time get replaced?",opts:["LRU", "FIFO", "LFU", "Optimal"],ans:3},
    {q:"Which of these is an example of a DDL command?",opts:["SELECT", "COMMIT", "ALTER", "GRANT"],ans:2},
    {q:"What is the output?\nd={1:'a',2:'b'}\nprint(d.get(3,'z'))",opts:["None", "Error", "3", "z"],ans:3},
    {q:"A train runs at 60 km/h. How many seconds to cross a 300m platform if train length is 300m?",opts:["30s", "36s", "40s", "72s"],ans:1},
    {q:"What is a copy constructor?",opts:["Constructor that copies values from another object of same class", "Constructor that copies from a different class", "Default constructor with copied parameters", "Constructor inside a copy class"],ans:0},
    {q:"In a class of 30, rank of Ravi from top is 11. What is his rank from bottom?",opts:["18", "19", "20", "21"],ans:2},
    {q:"Which of the following causes cascading rollback?",opts:["Dirty reads", "Lost update", "Phantom reads", "Deadlock"],ans:0},
    {q:"Which join returns only matching records?",opts:["LEFT JOIN", "RIGHT JOIN", "FULL JOIN", "INNER JOIN"],ans:3},
    {q:"If 5 machines make 5 widgets in 5 minutes, how long for 100 machines to make 100?",opts:["100 min", "20 min", "5 min", "1 min"],ans:2},
    {q:"Which normal form deals with Multivalued Dependency?",opts:["3NF", "BCNF", "4NF", "5NF"],ans:2},
    {q:"In Python, what is the output of 2 ** 3 ** 2?",opts:["64", "512", "256", "12"],ans:1},
    {q:"Time complexity to build a Heap of $n$ elements?",opts:["O(n log n)", "O(n)", "O(log n)", "O(n^2)"],ans:1},
    {q:"Which of these handles external fragmentation?",opts:["Paging", "Segmentation", "Compaction", "Swapping"],ans:2},
    {q:"In C++, a friend function has access to:",opts:["Private members", "Only Public", "Protected only", "No members"],ans:0},
    {q:"SQL: SELECT COUNT(*) on a table with 5 rows (one is NULL)?",opts:["4", "5", "0", "Error"],ans:1},
    {q:"Which data structure is used for BFS?",opts:["Stack", "Queue", "Linked List", "Tree"],ans:1},
    {q:"What is True + True in Python?",opts:["1", "2", "Error", "True"],ans:1},
    {q:"In E-R diagram, a double rectangle represents:",opts:["Weak Entity", "Strong Entity", "Relationship", "Attribute"],ans:0},
    {q:"Output of list(range(5, 2, -1)) in Python?",opts:["[5, 4, 3, 2]", "[5, 4, 3]", "[2, 3, 4, 5]", "[]"],ans:1},
    {q:"How many binary trees can be formed with 3 distinct nodes?",opts:["3", "4", "5", "6"],ans:2},
    {q:"Which sorting algorithm has the best average-case complexity?",opts:["Bubble Sort", "Insertion Sort", "Merge Sort", "Selection Sort"],ans:2},
    {q:"Which page replacement policy uses the past to predict the future?",opts:["FIFO", "LRU", "Optimal", "LFU"],ans:1},
    {q:"In SQL, what happens when you GROUP BY a column not in SELECT?",opts:["Syntax error", "Works in MySQL but not standard SQL", "Always fails", "Groups silently"],ans:1},
    {q:"What is the output of:\nfrom functools import reduce\nprint(reduce(lambda a,b: a+b, [1,2,3,4], 10))?",opts:["10", "20", "100", "Error"],ans:1},
    {q:"In C++, which of the following is true about abstract classes?",opts:["They can be instantiated via pointer only", "They cannot have constructors", "They can have non-abstract methods", "They must override all virtual functions"],ans:2},
    {q:"Relation R has FD: A→B, B→C, C→A. What is the candidate key?",opts:["A only", "B only", "C only", "All of A, B, C are candidate keys"],ans:3},
    {q:"What does the volatile keyword in C NOT guarantee?",opts:["Prevents compiler optimization", "Atomicity", "Prevents caching", "Forces re-read from memory"],ans:1},
    {q:"In C++, what is object slicing?",opts:["Copying only base class part when assigning derived to base", "Deleting part of an object", "Memory fragmentation", "Virtual table mismatch"],ans:0},
    {q:"Order of destruction? (Base destructor NOT virtual)\nBase *b = new Derived();\ndelete b;",opts:["Derived then Base", "Base only", "Derived only", "Undefined behavior"],ans:1},
    {q:"What is printed?\n\nDECLARE \n  x NUMBER := 10;\nBEGIN\n  x := x + NULL;\n  DBMS_OUTPUT.PUT_LINE(x);\nEND;",opts:["NULL", "10", "0", "Error"],ans:0},
  ]},
  {id:"lvl5",name:"LEVEL 5",icon:"🏗️ 🌐 ⚡",desc:"Pool 5",badge:"hard",timerSeconds:30,damagePerHit:20,buffer:[
    {q:"What will be output?\nclass A { void show(){ System.out.print(\"A\"); } }\nclass B extends A { void show(){ System.out.print(\"B\"); } }\nA obj = new B(); obj.show();",opts:["A", "B", "Error", "AB"],ans:1},
    {q:"In a B+ Tree, where are the actual data pointers or records stored?",opts:["Only in leaf nodes", "Only in internal nodes", "Both leaf and internal nodes", "At the root node only"],ans:0},
    {q:"Which protocol ensures that a transaction either commits fully or rolls back completely?",opts:["Two-Phase Locking", "Two-Phase Commit", "Thomas Write Rule", "Timestamp Ordering"],ans:1},
    {q:"What is the \"Wait-Die\" scheme used for in DBMS?",opts:["Query Optimization", "Deadlock Prevention", "Indexing", "Backup Recovery"],ans:1},
    {q:"What does typeid operator return?",opts:["type_info object", "string", "integer", "boolean"],ans:0},
    {q:"Which of the following anomalies is removed by 1NF?",opts:["Insertion anomaly", "Update anomaly", "Deletion anomaly", "Repeating groups"],ans:3},
    {q:"Which of these is NOT a valid access specifier in C++?",opts:["public", "private", "protected", "internal"],ans:3},
    {q:"In Dijkstra's algorithm, which data structure gives the best time complexity?",opts:["Array", "Stack", "Min-Heap / Priority Queue", "Linked List"],ans:2},
    {q:"Which of the following is TRUE about a Hash Table with chaining?",opts:["Worst case search is O(1)", "Worst case search is O(n)", "It cannot handle collisions", "Requires sorted data"],ans:1},
    {q:"What does delete[] do differently than delete?",opts:["Nothing different", "Frees array memory and calls destructor for each element", "Only frees first element", "Used for stack memory"],ans:1},
    {q:"What is the output? (static method hiding)\nA obj = new B();\nobj.show();",opts:["B", "AB", "A", "Error"],ans:2},
    {q:"Relation R(A,B,C) has FDs: A->B, B->C. Which normal form is violated if A is the only key?",opts:["1NF", "2NF", "3NF", "BCNF"],ans:2},
    {q:"What is the output?\nint arr[3]={0};\nint *p=arr;\n*(p+1)=5;\nprintf(\"%d\",arr[1]);",opts:["0", "5", "Garbage", "Error"],ans:1},
    {q:"What is the output?\nx=[1,2,3]\ny=x\ny.append(4)\nprint(len(x))",opts:["3", "4", "Error", "0"],ans:1},
    {q:"Which graph traversal detects a cycle in a directed graph?",opts:["BFS only", "DFS with back-edge detection", "Inorder traversal", "Dijkstra"],ans:1},
    {q:"What is a phantom read?",opts:["Reading a deleted row", "A transaction reads different values for same row twice", "New rows appear in a re-read due to another transaction's insert", "Reading NULL values"],ans:2},
    {q:"What is priority inversion?",opts:["High priority process runs before low priority", "Low priority process blocks high priority one indirectly", "CPU switches priority algorithms", "All processes get equal priority"],ans:1},
    {q:"What is the output?\ndef f(x=[]):\n    x.append(1)\n    return x\nprint(f(), f())",opts:["[1] [1]", "[1] [1,1]", "Error", "[1,1] [1,1]"],ans:1},
    {q:"Which schedule is conflict-serializable but NOT view-serializable?",opts:["All conflict-serializable are view-serializable", "A schedule with blind writes that isn't conflict-serializable", "They are always identical", "View-serializable is stricter"],ans:1},
    {q:"Which scheduling issue causes a low-priority process to block a high-priority one indirectly?",opts:["Starvation", "Deadlock", "Priority inversion", "Aging"],ans:2},
    {q:"Which algorithm guarantees deadlock avoidance?",opts:["FIFO", "BANKERs", "Round Robin", "LRU"],ans:1},
    {q:"Which condition causes deadlock?",opts:["Mutual exclusion", "Hold and wait", "Circular wait", "All of the above"],ans:3},
    {q:"Which type of key is minimal super key?",opts:["Primary key", "Candidate key", "Foreign key", "Composite key"],ans:1},
    {q:"Which of the following ensures durability in DBMS?",opts:["Buffer memory", "Cache", "Log files", "CPU"],ans:2},
    {q:"Which of the following leads to phantom read problem?",opts:["Same row update", "Insert/delete affecting query result", "Dirty read", "Lost update"],ans:1},
    {q:"A B-Tree of order 4 can have a maximum of how many keys per node?",opts:["4", "3", "2", "5"],ans:1},
    {q:"Concurrency protocol ensuring conflict serializability and no deadlock?",opts:["2PL", "Rigorous 2PL", "Timestamp", "Thomas Rule"],ans:2},
    {q:"Space complexity of a recursive DFS on a graph with $V$ vertices?",opts:["O(V)", "O(E)", "O(V+E)", "O(1)"],ans:0},
    {q:"In Java, can we override a static method?",opts:["Yes", "No", "Only in Interfaces", "If Public"],ans:1},
    {q:"What is the \"Dirty Read\" problem?",opts:["Reading committed", "Reading uncommitted", "Reading deleted", "Reading twice"],ans:1},
    {q:"What is the output?\nprint(set([1, 1, 2, 3]))",opts:["{1, 1, 2, 3}", "{1, 2, 3}", "[1, 2, 3]", "(1, 2, 3)"],ans:1},
    {q:"Number of null pointers in a binary tree with $n$ nodes?",opts:["$n$", "$n-1$", "$n+1$", "$2n$"],ans:2},
    {q:"In Java, which of the following is NOT a primitive type?",opts:["int", "char", "String", "boolean"],ans:2},
    {q:"What is the output?\nprint(bool(0), bool(''), bool([0]))",opts:["False False False", "False False True", "True True True", "False True False"],ans:1},
    {q:"In a max-heap, where is the smallest element always found?",opts:["Root", "Last leaf", "Any leaf", "Second level"],ans:2},
    {q:"What does the SQL COALESCE function do?",opts:["Joins two columns", "Returns first non-NULL value", "Removes duplicates", "Converts types"],ans:1},
    {q:"What is the output?\nint x=10;\nint* p=&x;\ncout << *p + 1;",opts:["10", "11", "Address+1", "Undefined"],ans:1},
    {q:"In a directed graph, which DFS edge type indicates a cycle?",opts:["Tree edge", "Forward edge", "Back edge", "Cross edge"],ans:2},
    {q:"In Java, method hiding occurs when:",opts:["A subclass has a method with same name and different parameters", "A subclass defines a static method with same signature as parent", "A subclass uses super keyword", "A private method is redefined"],ans:1},
    {q:"What is the output?\nclass A:\n def __init__(self): self.x=1\n def show(self): print(self.x)\nclass B(A):\n def __init__(self): self.x=2\nb=B()\nA.show(b)",opts:["1", "2", "Error", "None"],ans:1},
    {q:"Which normal form is violated if R(A,B,C,D) has FD A→B and {A,C} is the only key?",opts:["1NF", "2NF", "3NF", "BCNF"],ans:1},
    {q:"In Java, output of:\nString a = new String(\"hi\");\nString b = new String(\"hi\");\nSystem.out.println(a==b);?",opts:["1", "False", "Error", "Depends on JVM"],ans:1},
    {q:"In OS, what is thrashing?",opts:["High CPU utilization", "Process spending more time paging than executing", "Too many processes terminated", "Cache overflow"],ans:1},
    {q:"What is the output?\ndef gen():\n yield 1\n yield 2\ng = gen()\nnext(g)\nprint(next(g))?",opts:["1", "2", "None", "StopIteration"],ans:1},
    {q:"Which isolation level prevents dirty reads but NOT phantom reads?",opts:["Read Uncommitted", "Read Committed", "Repeatable Read", "Serializable"],ans:1},
    {q:"A schedule S is conflict-serializable if and only if:",opts:["Its precedence graph is a DAG", "It is strict", "It has no dirty reads", "It uses 2PL"],ans:0},
    {q:"What is the output?\nint a[]={1,2,3,4,5};\nint *p=a+1;\nprintf(\"%d\",*(p+2)-*(p-1));",opts:["2", "3", "4", "5"],ans:1},
    {q:"What is the output?\ntry:\n raise ValueError\nexcept Exception as e:\n print(type(e).__name__)?",opts:["Exception", "ValueError", "RuntimeError", "TypeError"],ans:1},
    {q:"In a B+ tree of order 5, what is the minimum number of keys in a non-root leaf node?",opts:["1", "2", "3", "4"],ans:1},
    {q:"Which of these deadlock handling strategies is used by most OS?",opts:["Prevention", "Avoidance", "Detection & Recovery", "Ostrich Algorithm"],ans:3},
    {q:"What is the output?\nclass X:\n def __new__(cls):\n print('new')\n return super().__new__(cls)\n def __init__(self):\n print('init')\nX()",opts:["init only", "new only", "new then init", "init then new"],ans:2},
    {q:"In Dijkstra's algorithm, what happens if a negative edge weight exists?",opts:["It gives correct answer", "It may give wrong answer", "It throws error", "It ignores negatives"],ans:1},
    {q:"What is a spurious wakeup in OS?",opts:["A thread wakes with no signal", "A thread sleeps indefinitely", "A deadlock condition", "A priority inversion"],ans:0},
    {q:"What is the output?\nint a=3,b=4,c=5;\nprintf(\"%d\",a<b<c);",opts:["1", "False", "True", "Undefined"],ans:0},
    {q:"What is the initial value of a binary semaphore?",opts:["0 or 1", "Only 0", "Only 1", "-1"],ans:0},
    {q:"Which solution guarantees mutual exclusion?",opts:["Peterson’s Algorithm", "FIFO Scheduling", "Paging", "Thrashing"],ans:0},
    {q:"Logical address space = 32 bits  Page size = 4 KB\nNumber of bits in page number:",opts:["20", "12", "16", "24"],ans:0},
    {q:"Which algorithm is stack algorithm?",opts:["FIFO", "LRU", "Random", "Second Chance"],ans:1},
    {q:"Peterson’s solution works for:",opts:["Any number of processes", "Only 2 processes", "Only 1 process", "Infinite processes"],ans:1},
    {q:"Which allocation method gives best random access and no fragmentation?",opts:["Contiguous", "Linked", "Indexed", "Hashed"],ans:2},
    {q:"System calls are used to:",opts:["Access hardware directly", "Interface between user and OS", "Execute programs", "Manage memory only"],ans:1},
    {q:"Which strategy suffers most from external fragmentation?",opts:["First Fit", "Best Fit", "Worst Fit", "Paging"],ans:1},
    {q:"A system has 3 processes and 3 resource types (1 instance each).\nIf each process holds one resource and requests another:Which statement is correct?",opts:["Deadlock cannot occur", "Deadlock will always occur", "Deadlock may occur", "System is safe"],ans:2},
    {q:"Which condition ensures no starvation?",opts:["Mutual exclusion", "Progress", "Bounded waiting", "Deadlock freedom"],ans:2},
    {q:"Thrashing mainly occurs due to:",opts:["Large CPU burst", "Insufficient frames", "High disk speed", "Low multiprogramming"],ans:1},
    {q:"Time complexity of merging two sorted linked lists:",opts:["O(n²)", "O(n+m)", "O(log n)", "O(n log n)"],ans:1},
  ]},
  {id:"lvl6",name:"LEVEL 6",icon:"🔥 🛡️ 🚀",desc:"Pool 6",badge:"hard",timerSeconds:30,damagePerHit:20,buffer:[
    {q:"Which isolation level is the highest and prevents \"Dirty Reads,\" \"Non-repeatable Reads,\" and \"Phantom Reads\"?",opts:["Read Uncommitted", "Read Committed", "Repeatable Read", "Serializable"],ans:3},
    {q:"In a B-Tree of order m, what is the minimum number of keys a non-root internal node must contain?",opts:["m-1", "[m/2]", "[m/2]-1", "m/2"],ans:2},
    {q:"What is the default access specifier in a class?",opts:["public", "protected", "internal", "private"],ans:3},
    {q:"Output of:\nint a=5;\ncout << ++a + a++;",opts:["10", "11", "12", "Undefined"],ans:3},
    {q:"A man has 3 daughters. Each daughter has 1 brother. Total children?",opts:["3", "4", "5", "6"],ans:1},
    {q:"Which comes next logically?\nMonday, Thursday, Sunday, ?",opts:["Tuesday", "Wednesday", "Thursday", "Friday"],ans:1},
    {q:"A farmer has 17 sheep. All but 9 die. How many are left?",opts:["8", "9", "17", "0"],ans:1},
    {q:"Find next: 1, 4, 9, 16, 25, ?",opts:["30", "35", "36", "49"],ans:2},
    {q:"What does the `new` keyword do in Java?",opts:["Declares a variable", "Allocates memory for an object", "Imports a class", "Deletes an object"],ans:1},
    {q:"What is the maximum number of children a node can have in a binary tree?",opts:["1", "3", "2", "Unlimited"],ans:2},
    {q:"Which feature allows same function name but different behavior at runtime?",opts:["Overloading", "Overriding", "Encapsulation", "Constructor"],ans:1},
    {q:"What is the output?\nint x=4;\nprintf(\"%d\", x>>1);",opts:["8", "1", "2", "4"],ans:2},
    {q:"What does \"hello\"[1:4] return?",opts:["hell", "ell", "ello", "hel"],ans:1},
    {q:"If a method is declared `final` in Java, it means:",opts:["It cannot be overloaded", "It cannot be overridden", "It runs first", "It is static"],ans:1},
    {q:"In Java, if class A implements interfaces B and C, both having a default method show(), what happens?",opts:["B's method is used", "C's method is used", "Compile error unless A overrides show()", "Runtime error"],ans:2},
    {q:"In MVCC, what does it primarily avoid?",opts:["Deadlocks only", "Read-write conflicts without locking readers", "Phantom reads entirely", "All anomalies"],ans:1},
    {q:"What is the output? (x=1)\nswitch(x){\n  case 1: printf(\"One\");\n  case 2: printf(\"Two\");\n  default: printf(\"Def\");\n}",opts:["One", "OneTwoDef", "OneTwo", "One Two"],ans:1},
    {q:"What is the time complexity of Kruskal's algorithm on a graph with V vertices and E edges?",opts:["O(V^2)", "O(E log V)", "O(E log E)", "O(V log E)"],ans:2},
    {q:"Which dependency leads to partial dependency?",opts:["Non-key → key", "Key → non-key", "Part of key → non-key", "Non-key → non-key"],ans:2},
    {q:"Which SQL query finds second highest salary correctly?",opts:["MAX(salary)", "MIN(salary)", "salary < (SELECT MAX(salary))", "MAX(salary) WHERE salary < MAX(salary)"],ans:2},
    {q:"Which type of lock allows multiple reads but no write?",opts:["Exclusive lock", "Shared lock", "Binary lock", "Intent lock"],ans:1},
    {q:"Which problem occurs when two transactions update same data simultaneously?",opts:["Dirty read", "Lost update", "Phantom read", "Deadlock"],ans:1},
    {q:"Which SQL clause filters groups after aggregation?",opts:["WHERE", "HAVING", "GROUP BY", "ORDER BY"],ans:1},
    {q:"Consider relation R(A, B, C) with FDs:A → B, B → C.  Which normal form is R in?",opts:["1NF", "2NF", "3NF", "BCNF"],ans:1},
    {q:"What is the output?\nprint(0.1 + 0.2 == 0.3)",opts:["1", "False", "0.3", "Machine Dependent"],ans:1},
    {q:"Which of these cannot be inherited in Java?",opts:["Public methods", "Constructors", "Protected fields", "Default methods"],ans:1},
    {q:"Which data structure is used to convert Infix to Postfix?",opts:["Queue", "Tree", "Stack", "Heap"],ans:2},
    {q:"Worst-case time complexity of QuickSort?",opts:["O(n log n)", "O(n)", "O(n^2)", "O(log n)"],ans:2},
    {q:"Normal form strictly stronger than 3NF but weaker than 4NF?",opts:["2NF", "BCNF", "5NF", "1NF"],ans:1},
    {q:"Primary issue to avoid in Dining Philosophers?",opts:["Deadlock", "Starvation", "Both A and B", "Race"],ans:2},
    {q:"Output of 5 < 6 < 3 in Python?",opts:["True", "False", "Error", "1"],ans:1},
    {q:"Why is B+ Tree preferred over Hash for indexing?",opts:["Hash is slow", "Supports range query", "Less memory", "Faster insert"],ans:1},
    {q:"Height of an AVL tree with $n$ nodes?",opts:["O(n)", "O(log n)", "O(n log n)", "O(1)"],ans:1},
    {q:"C++ mechanism for a class to access private data of another?",opts:["Inheritance", "Encapsulation", "Friendship", "Polymorphism"],ans:2},
    {q:"What does the volatile keyword prevent?",opts:["Multi-threading", "Caching optimization", "Memory leaks", "Recursion"],ans:1},
    {q:"In OS, what does TLB stand for?",opts:["Translation Lookup Buffer", "Thread Level Block", "Translation Lookaside Buffer", "Table Loaded Bit"],ans:2},
    {q:"Which SQL keyword prevents duplicate function calls in a GROUP BY query?",opts:["DISTINCT", "UNIQUE", "FILTER", "LIMIT"],ans:0},
    {q:"A full binary tree with n leaf nodes has how many total nodes?",opts:["n-1", "2n-1", "2n", "n+1"],ans:1},
    {q:"Which condition must hold for Banker's Algorithm to work?",opts:["Maximum resource need must be known in advance", "Resources are infinite", "No circular wait", "Preemption is allowed"],ans:0},
    {q:"What is the output of:\nclass A:\n x = 5\na = A()\na.x = 10\nprint(A.x)?",opts:["10", "5", "Error", "None"],ans:1},
    {q:"Consider: T1 reads X, T2 reads X, T1 writes X, T2 writes X. This is an example of:",opts:["Dirty Read", "Lost Update", "Phantom Read", "Deadlock"],ans:1},
    {q:"In Python, what is the output of:\nx = [1,2,3]\ny = x[:]\ny.append(4)\nprint(len(x))?",opts:["3", "4", "Error", "7"],ans:0},
    {q:"What is the worst-case time complexity of insertion in an AVL tree?",opts:["O(1)", "O(log n)", "O(n)", "O(n log n)"],ans:1},
    {q:"What is the time complexity of Prim's algorithm using a Fibonacci Heap?",opts:["O(E log V)", "O(E + V log V)", "O(V^2)", "O(E log E)"],ans:1},
    {q:"Which of the following is TRUE about MVCC?",opts:["Writers block readers", "Readers block writers", "Each transaction sees a snapshot", "It requires 2PL"],ans:2},
    {q:"In Python, what is the output of:\nx = (i for i in range(3))\nlist(x)\nprint(list(x))?",opts:["[0,1,2]", "[]", "Error", "[0,1,2,0,1,2]"],ans:1},
    {q:"Relation R(A,B,C,D,E) FDs: AB→C, C→D, D→E. If AB is the key, which NF is violated?",opts:["2NF", "3NF", "BCNF", "4NF"],ans:1},
    {q:"What is the output?\ndef outer():\n x = 10\n def inner():\n nonlocal x\n x += 5\n return x\n return inner()\nprint(outer())",opts:["10", "15", "Error", "None"],ans:1},
    {q:"In a concurrent system, if T1 holds lock on A and waits for B, and T2 holds B and waits for C, and T3 holds C and waits for A — the system has:",opts:["Starvation", "Deadlock", "Livelock", "Priority Inversion"],ans:1},
    {q:"In Python, what is the output of:         a = \"hello\"\n                                                            b = \"hello\"\n                                                             print(a is b)",opts:["True", "False", "Error", "None"],ans:0},
    {q:"Which algorithm gives minimum average waiting time?",opts:["FCFS", "SJF", "Round Robin", "Priority"],ans:1},
    {q:"Time complexity (without tail pointer):",opts:["O(1)", "O(log n)", "O(n)", "O(n²)"],ans:2},
    {q:"Node* p = head;\nNode* q = head;\n\nwhile(q && q->next) {\n    p = p->next;\n    q = q->next->next;\n}\n\nWhat does p represent at end?",opts:["First node", "Last node", "Middle node", "Random node"],ans:2},
    {q:"Which causes memory leak?",opts:["Not deleting nodes", "Using pointers", "Traversing list", "Reversing list"],ans:0},
    {q:"Node* head = new Node{10, nullptr};\nhead->next = new Node{20, nullptr};\nhead->next->next = new Node{30, nullptr};\nNode* temp = head;\ntemp->next = temp->next->next;\ncout << head->next->data;\n\nOutput?",opts:["20", "30", "10", "error"],ans:1},
    {q:"head->next->next->next = head;\nWhat happens?",opts:["List ends", "Cycle created", "Error", "List reversed"],ans:1},
  ]},
];



/* getLevels kept as alias for compatibility */
function getLevels(){return FIXED_LEVELS;}
